// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSpFqcCN7yje-1zKNydtV8-QbSfJb2VyU',
    appId: '1:35779139020:web:b2463b486864610ab27969',
    messagingSenderId: '35779139020',
    projectId: 'skill-match-71500',
    authDomain: 'skill-match-71500.firebaseapp.com',
    storageBucket: 'skill-match-71500.firebasestorage.app',
    measurementId: 'G-8S0WFY8VN0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNet0YLwXG-xgJYFETFYjYdyRLx1FZYQc',
    appId: '1:35779139020:android:4c2bb3c2787287a0b27969',
    messagingSenderId: '35779139020',
    projectId: 'skill-match-71500',
    storageBucket: 'skill-match-71500.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOwQBTHP7jHsyuwjsUyKB0LUpm_PlqVHg',
    appId: '1:35779139020:ios:9927730a7d7d783db27969',
    messagingSenderId: '35779139020',
    projectId: 'skill-match-71500',
    storageBucket: 'skill-match-71500.firebasestorage.app',
    iosBundleId: 'pt.iscte.skillMatch',
  );
}
